export {
  dynamodbClient,
  docClient,
  getTableName,
  TABLE_NAME,
  resetClient,
  createEntityKey,
  createSystemKey,
  createGSIKey,
  ENTITY_TYPES,
  DATA_CATEGORIES,
  type EntityType,
  type DataCategory,
  type DynamoDBItem,
  putItem,
  getItem,
  updateItem,
  deleteItem,
  queryItems,
  scanItems,
  batchWriteItems,
  batchGetItems,
  tableExists,
  listTables,
  createTableIfNotExists,
  enableTTL,
  getDynamoDBClient,
  getDynamoDBDocClient,
} from './dynamodb';
export {
  getFromCache,
  setCache,
  deleteFromCache,
  existsInCache,
  incrementRateLimit,
  getRateLimit,
  resetRateLimit,
  setRateLimitLock,
  isRateLimitLocked,
  generateCacheKey,
  CacheKeys,
  checkCacheHealth,
  clearCacheByPattern,
  type CacheType,
  type RateLimitKeyType,
} from './cache';
