/**
 * Test Data Generator
 *
 * Utilities for generating and managing test data for E2E tests.
 */

import type { CourseData } from '../../../data/courseData';

// Extended course data for pagination testing (courses 16-30)
export const PAGINATION_TEST_COURSES: CourseData[] = [
  {
    id: '16',
    title: '日语入门课程',
    price: 45,
    lessonCount: 10,
    lessonDuration: 60,
    rating: 4.7,
    reviewCount: 45,
    city: 'auckland',
    region: 'Auckland CBD',
    subject: '语言',
    grade: '成人',
    teacherName: '山本老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '日文授课',
    schedule: '平日晚上',
  },
  {
    id: '17',
    title: '韩语发音基础',
    price: 40,
    lessonCount: 8,
    lessonDuration: 45,
    rating: 4.6,
    reviewCount: 32,
    city: 'auckland',
    region: 'Newmarket',
    subject: '语言',
    grade: '成人',
    teacherName: '金老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '韩文授课',
    schedule: '周末上午',
  },
  {
    id: '18',
    title: '法语初级班',
    price: 50,
    lessonCount: 12,
    lessonDuration: 60,
    rating: 4.8,
    reviewCount: 58,
    city: 'wellington',
    region: 'Wellington CBD',
    subject: '语言',
    grade: '成人',
    teacherName: 'Marie老师',
    trustLevel: 'S',
    teachingMode: 'offline',
    language: '法文授课',
    schedule: '平日晚上',
  },
  {
    id: '19',
    title: '西班牙语会话',
    price: 42,
    lessonCount: 10,
    lessonDuration: 60,
    rating: 4.5,
    reviewCount: 28,
    city: 'christchurch',
    region: 'Riccarton',
    subject: '语言',
    grade: '成人',
    teacherName: 'Carlos老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '西班牙语授课',
    schedule: '周末下午',
  },
  {
    id: '20',
    title: '中文汉字书法',
    price: 38,
    lessonCount: 8,
    lessonDuration: 90,
    rating: 4.9,
    reviewCount: 67,
    city: 'auckland',
    region: 'Remuera',
    subject: '艺术',
    grade: '全年龄',
    teacherName: '陈书法家',
    trustLevel: 'S',
    teachingMode: 'offline',
    language: '中文授课',
    schedule: '周末上午',
  },
  {
    id: '21',
    title: '高考英语强化',
    price: 55,
    lessonCount: 16,
    lessonDuration: 90,
    rating: 4.7,
    reviewCount: 89,
    city: 'online',
    region: 'Online',
    subject: '英语',
    grade: '高中',
    teacherName: '赵老师',
    trustLevel: 'A',
    teachingMode: 'online',
    language: '中文授课',
    schedule: '平日晚上',
  },
  {
    id: '22',
    title: '少儿编程启蒙',
    price: 48,
    lessonCount: 12,
    lessonDuration: 60,
    rating: 4.8,
    reviewCount: 112,
    city: 'auckland',
    region: 'Mt Eden',
    subject: '编程',
    grade: '小学',
    teacherName: '刘老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '中文授课',
    schedule: '周末下午',
  },
  {
    id: '23',
    title: 'SAT 数学冲刺',
    price: 60,
    lessonCount: 10,
    lessonDuration: 90,
    rating: 4.9,
    reviewCount: 76,
    city: 'online',
    region: 'Online',
    subject: '数学',
    grade: '高中',
    teacherName: '张老师',
    trustLevel: 'S',
    teachingMode: 'online',
    language: '英文授课',
    schedule: '周末上午',
  },
  {
    id: '24',
    title: 'NCEA 生物高分班',
    price: 52,
    lessonCount: 14,
    lessonDuration: 60,
    rating: 4.6,
    reviewCount: 54,
    city: 'auckland',
    region: 'Epsom',
    subject: '理科',
    grade: '高中',
    teacherName: '吴老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '中文授课',
    schedule: '平日晚上',
  },
  {
    id: '25',
    title: '高尔夫球初学',
    price: 80,
    lessonCount: 6,
    lessonDuration: 90,
    rating: 4.8,
    reviewCount: 23,
    city: 'auckland',
    region: 'Howick',
    subject: '体育',
    grade: '成人',
    teacherName: '王教练',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '中文授课',
    schedule: '周末下午',
  },
  {
    id: '26',
    title: '瑜伽冥想课程',
    price: 35,
    lessonCount: 10,
    lessonDuration: 60,
    rating: 4.7,
    reviewCount: 41,
    city: 'auckland',
    region: 'Parnell',
    subject: '体育',
    grade: '成人',
    teacherName: 'Lisa老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '英文授课',
    schedule: '平日早晨',
  },
  {
    id: '27',
    title: '尤克里里弹唱',
    price: 42,
    lessonCount: 8,
    lessonDuration: 45,
    rating: 4.9,
    reviewCount: 36,
    city: 'wellington',
    region: 'Karori',
    subject: '音乐',
    grade: '全年龄',
    teacherName: '高老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '中文授课',
    schedule: '周末上午',
  },
  {
    id: '28',
    title: '科学实验探索',
    price: 50,
    lessonCount: 10,
    lessonDuration: 90,
    rating: 4.8,
    reviewCount: 62,
    city: 'christchurch',
    region: 'Fendalton',
    subject: '理科',
    grade: '小学',
    teacherName: '钱老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '中文授课',
    schedule: '周末下午',
  },
  {
    id: '29',
    title: '辩论与演讲',
    price: 48,
    lessonCount: 12,
    lessonDuration: 60,
    rating: 4.6,
    reviewCount: 48,
    city: 'auckland',
    region: 'Grey Lynn',
    subject: '英语',
    grade: '初中',
    teacherName: 'Michael老师',
    trustLevel: 'A',
    teachingMode: 'offline',
    language: '英文授课',
    schedule: '平日晚上',
  },
  {
    id: '30',
    title: '历史人文探究',
    price: 40,
    lessonCount: 10,
    lessonDuration: 60,
    rating: 4.7,
    reviewCount: 35,
    city: 'online',
    region: 'Online',
    subject: '文科',
    grade: '初中',
    teacherName: '周老师',
    trustLevel: 'A',
    teachingMode: 'online',
    language: '中文授课',
    schedule: '周末上午',
  },
];

// Test user accounts
export const TEST_USERS = {
  regular: {
    email: 'user@example.com',
    verificationCode: '123456',
  },
  rateLimited: {
    email: 'ratelimit@test.com',
    verificationCode: '123456',
  },
  banned: {
    email: 'banned@test.com',
    verificationCode: '123456',
  },
  wrongCode: {
    email: 'user@example.com',
    verificationCode: '000000',
  },
};

// Search test cases
export const SEARCH_TEST_CASES = [
  { keyword: '数学', expectedCount: 4 },
  { keyword: '英语', expectedCount: 3 },
  { keyword: '不存在的课程', expectedCount: 0 },
  { keyword: '', expectedCount: 15 }, // Empty keyword should return all courses
];

// Filter test combinations
export const FILTER_TEST_CASES = [
  { filters: { city: 'auckland' }, expectedMin: 15 },
  { filters: { city: 'online' }, expectedMin: 4 },
  { filters: { subject: '音乐' }, expectedMin: 3 },
  { filters: { grade: '高中' }, expectedMin: 5 },
];

// Helper to get courses by page for pagination testing
export function getCoursesForPage(
  allCourses: CourseData[],
  page: number,
  pageSize: number = 10
): CourseData[] {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  return allCourses.slice(start, end);
}

// Helper to generate pagination metadata
export function generatePaginationMeta(total: number, page: number, pageSize: number = 10) {
  return {
    page,
    pageSize,
    total,
    totalPages: Math.ceil(total / pageSize),
  };
}
